# Generated by Django 6.0.2 on 2026-04-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
